apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: dockerfile-assignment1
  name: dockerfile-assignment1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dockerfile-assignment1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: dockerfile-assignment1
    spec:
      containers:
      - image: <image>
        name: dockerfile-assignment1
        resources: {}
status: {}
