apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: dockerfile-assignment1
  name: dockerfile-assignment1-service
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: dockerfile-assignment1
  type: NodePort
status:
  loadBalancer: {}
